**ibm/nalaiya thiran/assignment1/sivasankar/10fives-numpy.py**

In [1]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**ibm/nalaiya thiran/assignment1/sivasankar/10zeros-numpy.py**

In [3]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**ibm/nalaiya thiran/assignment1/sivasankar/1split-basic.py**

In [4]:
string = "Hi there Sam!"
print(string.split())

['Hi', 'there', 'Sam!']


**ibm/nalaiya thiran/assignment1/sivasankar/2col3row-panda.py**

In [15]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age']
print(df)

SyntaxError: ignored

**ibm/nalaiya thiran/assignment1/sivasankar/2d-panda.py**

In [8]:
import pandas as pd  

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 

df = pd.DataFrame(lists, columns =['ID', 'Name', 'Age']) 
print(df)

   ID Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24


**ibm/nalaiya thiran/assignment1/sivasankar/3d-numpy.py**

In [9]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**ibm/nalaiya thiran/assignment1/sivasankar/concat-numpy.py**

In [10]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)
print('\n---Result of a and b---')
print(np.concatenate((a, b)))

[1 2 3]
[4 5 6]

---Result of a and b---
[1 2 3 4 5 6]


**ibm/nalaiya thiran/assignment1/sivasankar/date-pandas.py**

In [11]:
import datetime
import pandas as pd

# initializing date
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")

# initializing periods
periods = datetime.datetime.strptime("02-02-2023", "%d-%m-%Y")

date_generated = pd.date_range(test_date, periods)
print(date_generated.strftime("%d-%m-%Y"))


Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023'],
      dtype='object')


**ibm/nalaiya thiran/assignment1/sivasankar/earth-basic.py**

In [12]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


**ibm/nalaiya thiran/assignment1/sivasankar/even-numpy.py**

In [13]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 36")
print(array)

Array of all the even integers from 20 to 36
[20 22 24 26 28 30 32 34]


**ibm/nalaiya thiran/assignment1/sivasankar/hello-basic.py**

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello
